### ISSUE TITLE
Error when enable magascan_link_python

### ISSUE THREAD

**Issue by sawyercheung** [Raider-Arts/painter-megascan-link#1]
[Plugin - megascan_link_js] Megascan-link-JS loaded
[Plugin - resources-updater] No project open, resources updater discarded
[Python] Adding dependecies
[Python] [megascanlink][ERROR] Error during pip command: Command '['C:\\Program Files\\Allegorithmic\\Substance Painter\\resources\\pythonsdk\\python.exe', '-m', 'pip', 'install', 'websocket-client']' returned non-zero exit status 3221225786.
[Python] [megascanlink][INFO] Check installed dependecies
[Python] [megascanlink][ERROR] Dependecies error! cannot start plugin
[Python] Failed to stop plugin megascan_link_python
[Python] AttributeError("'NoneType' object has no attribute 'close'")

**Comment by faggionluca** [comment]
hi @sawyercheung, yup that's a common error it mean that the automatic dependencies installation script failed to install the needed dependency, so you have to install it by hand by [following this guide ](https://painter-megascan-link.readthedocs.io/en/latest/user_guide_install.html#manual-dependencies-installation)

Let me know if you need help with the procedure 😄

**Comment by faggionluca** [comment]
hello @sawyercheung,  it's been a while and I didn't heard nothing from you, did you managed to get it working?
I hope so 😄

**Comment by sawyercheung** [comment]
Just followed your instructions and it works perfectly now!! 
Thank you

**Comment by faggionluca** [comment]
I'm glad you get it working and Thank you for using it 😃 !
