### ISSUE TITLE
tried manual install , didnt worked please help

### ISSUE THREAD

**Issue by superman4** [Raider-Arts/painter-megascan-link#3]
cd %pathtoSubtancePainter%\resources\pythonsdk
 this didnt worked so i manually browsed and opened powershell from there  and last line of code websocket 0.57.0
after all that . export failed 

when i reopened substance it says i need to install it manualy
please help
what i have to do , to fix it 

substance log

[Python] Adding dependecies
[Python] [megascanlink][ERROR] Error during pip command: Command '['C:\\Program Files\\Allegorithmic\\Substance Painter\\resources\\pythonsdk\\python.exe', '-m', 'pip', 'install', 'websocket-client']' returned non-zero exit status 1.
[Python] [megascanlink][INFO] Check installed dependecies
[Python] [megascanlink][ERROR] Dependecies error! cannot start plugin
[Plugin - megascan_link_js] Megascan-link-JS loaded
[Plugin - resources-updater] No project open, resources updater discarded
[Python] Failed to stop plugin megascan_link_python
[Python] AttributeError("'NoneType' object has no attribute 'close'")
[Python] Adding dependecies
[Python] [megascanlink][ERROR] Error during pip command: Command '['C:\\Program Files\\Allegorithmic\\Substance Painter\\resources\\pythonsdk\\python.exe', '-m', 'pip', 'install', 'websocket-client']' returned non-zero exit status 1.
[Python] [megascanlink][INFO] Check installed dependecies
[Python] [megascanlink][ERROR] Dependecies error! cannot start plugin

**Comment by superman4** [comment]
last line of code websocket 0.57.0     Not  as **per your code 0.x.x**
after all that . export failed

when i reopened substance it says i need to install it manualy
please help
what i have to do , to fix it

**Comment by faggionluca** [comment]
Hi @superman4 !
Let's try to resolve this fairly common issue, first thing to check, did you installed the dependency with this command `python.exe -m pip install websocket-client` and did it gave you any errors? 

**be sure to install websocket-client and not only websocket, the command `python.exe -m pip freeze` should report a line with websocket-client==0.57.0**

**Comment by superman4** [comment]
pip was outdated
fixed it
thank you
